# Make sure to check the documentation at http://goreleaser.com
version: 2
project_name: cascade
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    main: "./cmd/cascade"
    binary: "cascade"
    ldflags:
      - >-
        -s -w
        -X github.com/goliatone/cascade/pkg/version.Tag={{ .Version }}
        -X github.com/goliatone/cascade/pkg/version.Time={{ .Date }}
        -X github.com/goliatone/cascade/pkg/version.User=goreleaser
        -X github.com/goliatone/cascade/pkg/version.Commit={{ .FullCommit }}
archives:
  - id: cascade
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}
      {{- if .Arm }}armv{{ .Arm }}{{ else }}arm{{ end }}
      {{- else }}{{ .Arch }}{{ end -}}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^Update README"
      - "merge fix"
  format: '{{ .SHA }}: {{ .Message }} ({{ with .AuthorUsername }}@{{ . }}{{ else }}{{ .AuthorName }} <{{ .AuthorEmail }}>{{ end }})'
homebrew_casks:
  - name: cascade
    binaries:
      - cascade
    repository:
      owner: goliatone
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    description: managed release cycles.
    homepage: https://github.com/goliatone/cascade
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cascade"]
          end
nfpms:
  - id: cascade
    file_name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm" }}
      {{- if .Arm }}armv{{ .Arm }}{{ else }}arm{{ end }}
      {{- else }}{{ .Arch }}{{ end -}}
    bindir: /usr/local/bin/
    maintainer: goliatone <cascade@goliatone.com>
    description: managed release cycles.
    homepage: https://github.com/goliatone/cascade
    license: "MIT"
    formats:
      - deb
      - rpm
