name: "Release cascade"
on:
  push:
    tags:
      - v*.*.*
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: "Unshallow Fetch"
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v6
        with:
          go-version: "^1.22.1"
      - name: "Release via goreleaser"
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_HOMEBREW_TAP }}
      - name: "Create latest tag"
        uses: EndBug/latest-tag@latest
        with:
          description: "cascade latest release"
